### ISSUE TITLE
aws_base64_decode rejects the output of aws_base64_encode

### ISSUE THREAD

**Issue by bdonlan** [awslabs/aws-c-common#123]
`aws_base64_encode` appends a NUL-terminator to its output, which is included in the byte_buf's len count. However, `aws_base64_decode` calls out to `aws_base64_compute_decoded_len`, which assumes the length counts only the actual base64 encoded data, and rejects if this data is not a length that is a multiple of 4. With the NUL terminator, this check never passes, and so passing the output buffer from `aws_base64_encode` directly to `aws_base64_decode` always fails.

**Comment by ColdenCullen** [comment]
Why are we writing a terminator at all? I can't find any docs online that suggest doing that.

**Comment by bdonlan** [comment]
It's useful if you want to use the buffer in a C routine (fprintf, etc), but probably should not be counted against len.

**Comment by ColdenCullen** [comment]
Could you do something like we did in awslabs/aws-c-io#29 and append a null terminator, but not include it in the length?

**Comment by jonahharris** [comment]
Agreed. After looking through it, as aws_base64_compute_encoded_len is public and used (by the developer) to allocate the byte buffer, thinking we should let that still account for the null terminator, but update aws_base64_encode to set the byte buffer's len property such that the terminator is unaccounted for. All usages I can see in the test cases account for it by decrementing len prior to passing to aws_base64_decode, as referenced by op. Those are easy to update.

It appears this is also used in aws-crt-cpp and aws-c-event-stream libraries. In aws-crt-cpp, it's called in Base64Encode, there are no cases I can find of its use in tests or otherwise. In aws-c-event-stream, it's passed to fprintf and will work as-expected with the change.

A cursory search of base-64 encoding/decoding implementations seems to be a 60/40 split as far as not including vs including the null terminator in the length. So, I think we'd be fine not including it, which is also my preference. I did, however, notice [another AWS library implementation of b64](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-pic/src/utils/src/Base64.cpp#L52) that _does_ include the null terminator in the length.

Thoughts? I can code this fix up quickly if a decision is made. Likewise, should the same change be made for hex encoding?

**Comment by JonathanHenson** [comment]
@bdonlan agreed, null terminators should NEVER be counted against length. This one is my error, because the RFC unit test cases had empty string as a vector. We should leave the NULL terminator but not count it against length.

**Comment by ColdenCullen** [comment]
Hey this seems fixed?
